/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.rogerio.app;

import br.com.rogerio.model.Fila;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class FilaViewFuraFila extends javax.swing.JFrame {
    
    Fila fila;

    /**
     * Creates new form FilaViewFuraFila
     */
    public FilaViewFuraFila() {
        initComponents();
        fila = new Fila();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFilaFuraFila = new javax.swing.JPanel();
        jTextFieldInserirElemento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldResultManipulacaoDaFila = new javax.swing.JTextField();
        jButtonStatusDaFila = new javax.swing.JButton();
        jButtonQuantElementos = new javax.swing.JButton();
        jButtonInserirElemento = new javax.swing.JButton();
        jButtonConsultarPrimeiroDaFila = new javax.swing.JButton();
        jButtonRetirarElemento = new javax.swing.JButton();
        jButtonIncluirFuraFila = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Projeto Fila Exercicio 04 Fura-Fila");
        setResizable(false);

        jLabel1.setText("Inserir elemento inteiro na fila");

        jLabel2.setText("Status da fila");

        jTextFieldResultManipulacaoDaFila.setEditable(false);

        jButtonStatusDaFila.setText("Status da Fila");
        jButtonStatusDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatusDaFilaActionPerformed(evt);
            }
        });

        jButtonQuantElementos.setText("Quant. Elementos");
        jButtonQuantElementos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuantElementosActionPerformed(evt);
            }
        });

        jButtonInserirElemento.setText("Inserir Elemento");
        jButtonInserirElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirElementoActionPerformed(evt);
            }
        });

        jButtonConsultarPrimeiroDaFila.setText("Consultar o 1º da Fila");
        jButtonConsultarPrimeiroDaFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarPrimeiroDaFilaActionPerformed(evt);
            }
        });

        jButtonRetirarElemento.setText("Retirar Elemento");
        jButtonRetirarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarElementoActionPerformed(evt);
            }
        });

        jButtonIncluirFuraFila.setText("Incluir Fura-Fila");
        jButtonIncluirFuraFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirFuraFilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFilaFuraFilaLayout = new javax.swing.GroupLayout(jPanelFilaFuraFila);
        jPanelFilaFuraFila.setLayout(jPanelFilaFuraFilaLayout);
        jPanelFilaFuraFilaLayout.setHorizontalGroup(
            jPanelFilaFuraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaFuraFilaLayout.createSequentialGroup()
                .addGroup(jPanelFilaFuraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFilaFuraFilaLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanelFilaFuraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldInserirElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldResultManipulacaoDaFila, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFilaFuraFilaLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addGroup(jPanelFilaFuraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonQuantElementos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonStatusDaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonInserirElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonRetirarElemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIncluirFuraFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonConsultarPrimeiroDaFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanelFilaFuraFilaLayout.setVerticalGroup(
            jPanelFilaFuraFilaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFilaFuraFilaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldInserirElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldResultManipulacaoDaFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButtonStatusDaFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonQuantElementos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInserirElemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConsultarPrimeiroDaFila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRetirarElemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonIncluirFuraFila)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFilaFuraFila, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFilaFuraFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStatusDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatusDaFilaActionPerformed
        // TODO add your handling code here:
        try {
            if (fila.isEmpty()) {
                jTextFieldResultManipulacaoDaFila.setText("A fila está vazia!\n");
            }else if (fila.isFull()){
                jTextFieldResultManipulacaoDaFila.setText("A fila está cheia!\n");
            }else {
                jTextFieldResultManipulacaoDaFila.setText("Temos " + fila.size() + " elemento(s) na fila!");
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonStatusDaFilaActionPerformed

    private void jButtonQuantElementosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuantElementosActionPerformed
        // TODO add your handling code here:
        try {
            jTextFieldResultManipulacaoDaFila.setText("Temos " + fila.size() + " elemento(s) na fila!");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonQuantElementosActionPerformed

    private void jButtonInserirElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirElementoActionPerformed
        // TODO add your handling code here:
        try {
            fila.enqueue(Integer.parseInt(jTextFieldInserirElemento.getText()));
            jTextFieldResultManipulacaoDaFila.setText("Inserido um elemento");
            jTextFieldInserirElemento.requestFocus();
            jTextFieldInserirElemento.setText("");
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonInserirElementoActionPerformed

    private void jButtonConsultarPrimeiroDaFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarPrimeiroDaFilaActionPerformed
        // TODO add your handling code here:
        try {
            jTextFieldResultManipulacaoDaFila.setText("O primeiro elemento da fila é: " + fila.peek());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonConsultarPrimeiroDaFilaActionPerformed

    private void jButtonRetirarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarElementoActionPerformed
        // TODO add your handling code here:
        try {
            jTextFieldResultManipulacaoDaFila.setText("Retirando o elemento: " + fila.peek());
            fila.dequeue();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonRetirarElementoActionPerformed

    private void jButtonIncluirFuraFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirFuraFilaActionPerformed
        // TODO add your handling code here:
        try {
            fila.FuraFila(Integer.parseInt(jTextFieldInserirElemento.getText()));
            jTextFieldResultManipulacaoDaFila.setText("Inserido o fura fila > " + fila.peek());
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButtonIncluirFuraFilaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaViewFuraFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaViewFuraFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaViewFuraFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaViewFuraFila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaViewFuraFila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultarPrimeiroDaFila;
    private javax.swing.JButton jButtonIncluirFuraFila;
    private javax.swing.JButton jButtonInserirElemento;
    private javax.swing.JButton jButtonQuantElementos;
    private javax.swing.JButton jButtonRetirarElemento;
    private javax.swing.JButton jButtonStatusDaFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelFilaFuraFila;
    private javax.swing.JTextField jTextFieldInserirElemento;
    private javax.swing.JTextField jTextFieldResultManipulacaoDaFila;
    // End of variables declaration//GEN-END:variables
}
